"""Handler for pipeline.git.lfs_rules — scan asset types → .gitattributes LFS rules.

Scans a directory, detects binary asset extensions, and generates
appropriate .gitattributes LFS rules.

Outputs:
    lfs_rules.txt — ready-to-append .gitattributes content

Params:
    directory (str): directory to scan
"""
from __future__ import annotations

_AVAILABLE = True  # pure Python stdlib

# Well-known binary game asset extensions → LFS lock type
_LFS_RULES: list[tuple[str, str]] = [
    # 3D meshes
    ("*.glb",   "lockable"),
    ("*.gltf",  "lockable"),
    ("*.fbx",   "lockable"),
    ("*.obj",   "lockable"),
    ("*.ply",   "lockable"),
    ("*.stl",   "lockable"),
    ("*.dae",   "lockable"),
    # Textures
    ("*.png",   ""),
    ("*.jpg",   ""),
    ("*.jpeg",  ""),
    ("*.tga",   "lockable"),
    ("*.exr",   "lockable"),
    ("*.hdr",   "lockable"),
    ("*.webp",  ""),
    ("*.bmp",   ""),
    ("*.tiff",  "lockable"),
    # Audio
    ("*.wav",   "lockable"),
    ("*.ogg",   ""),
    ("*.mp3",   ""),
    ("*.flac",  "lockable"),
    ("*.aiff",  "lockable"),
    # Video / sprite
    ("*.mp4",   "lockable"),
    ("*.mov",   "lockable"),
    # Documents / archives
    ("*.psd",   "lockable"),
    ("*.pdf",   ""),
    ("*.zip",   ""),
    ("*.7z",    ""),
]


def run(job_type, params, model_id, model_path, device, progress_cb, output_dir):
    """Generate .gitattributes LFS rules from a directory scan."""
    from pathlib import Path

    directory = params.get("directory", "")
    if not directory:
        raise ValueError("'directory' parameter is required")
    dir_path = Path(directory)
    if not dir_path.is_dir():
        raise ValueError(f"Directory not found: {directory}")

    progress_cb(0.0, "Scanning extensions")
    found_exts: set[str] = set()
    for f in dir_path.rglob("*"):
        if f.is_file() and f.suffix:
            found_exts.add(f"*{f.suffix.lower()}")

    progress_cb(0.5, "Building LFS rules")
    lines: list[str] = [
        "# Git LFS rules — generated by assgen pipeline.git.lfs_rules",
        "# Paste into .gitattributes at the root of your repository.",
        "",
    ]

    matched: list[tuple[str, str]] = []
    for pattern, lock in _LFS_RULES:
        if pattern in found_exts or not found_exts:
            matched.append((pattern, lock))

    # Also add any found extensions not in the known list
    known_patterns = {p for p, _ in _LFS_RULES}
    for ext in sorted(found_exts - known_patterns):
        matched.append((ext, ""))

    for pattern, lock in matched:
        lock_part = " -lockable" if not lock else (" lockable" if lock == "lockable" else "")
        lines.append(f"{pattern} filter=lfs diff=lfs merge=lfs -text{lock_part}")

    content = "\n".join(lines) + "\n"
    out_path = Path(output_dir) / "lfs_rules.txt"
    out_path.write_text(content)

    progress_cb(1.0, "Done")
    return {
        "files": [str(out_path)],
        "metadata": {
            "rule_count": len(matched),
            "extensions_found": sorted(found_exts),
        },
    }
